theme: jekyll-theme-primer
title: Recommendations
description: Recommendations project report
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
